"use client";

import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { Award, ArrowLeft, MapPin, School, Sparkles } from "lucide-react";
import { backendApi } from "@/lib/api";
import { BoyAvatar } from "@/components/profile-avatar";
import { TeachingBadge } from "@/components/streak/reward-artifacts";

export default function FeaturedTeachersPage() {
  const teachers = useQuery({ queryKey: ["featured-teachers"], queryFn: backendApi.featuredTeachers });
  return (
    <main className="min-h-[100dvh] overflow-x-hidden bg-[radial-gradient(circle_at_top_left,#eff6ff,transparent_35%),radial-gradient(circle_at_top_right,#fef3c7,transparent_32%),#f8fafc] px-3 py-5 min-[390px]:px-4 min-[390px]:py-8 sm:py-14">
      <div className="mx-auto max-w-6xl">
        <Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-blue-600"><ArrowLeft className="h-4 w-4" /> Back to TeachPad</Link>
        <header className="mx-auto mt-7 max-w-3xl text-center min-[390px]:mt-10"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-blue-600 text-white shadow-lg shadow-blue-200 min-[390px]:h-14 min-[390px]:w-14"><Sparkles className="h-5 w-5 min-[390px]:h-6 min-[390px]:w-6" /></div><p className="mt-4 text-[10px] font-black uppercase tracking-[0.18em] text-blue-600 min-[390px]:mt-5 min-[390px]:text-xs min-[390px]:tracking-[0.2em]">TeachPad recognition</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950 min-[390px]:mt-3 min-[390px]:text-4xl sm:text-5xl">Featured Teachers</h1><p className="mt-3 text-xs font-medium leading-5 text-slate-600 min-[390px]:mt-4 min-[390px]:text-sm min-[390px]:leading-6 sm:text-base">Celebrating educators who consistently prepare thoughtful classroom resources. Every profile shown here was reviewed and explicitly approved by the teacher.</p></header>
        {teachers.isLoading ? <div className="mt-8 grid gap-4 min-[390px]:mt-12 min-[390px]:gap-5 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <div key={index} className="h-72 animate-pulse rounded-[22px] bg-white min-[390px]:h-80 min-[390px]:rounded-3xl" />)}</div> : teachers.isError ? <div className="mx-auto mt-8 max-w-lg rounded-2xl border border-rose-100 bg-white p-5 text-center text-sm font-semibold text-slate-600 min-[390px]:mt-12 min-[390px]:p-6">Featured teacher profiles could not be loaded right now.</div> : teachers.data?.items.length ? <section className="mt-8 grid gap-4 min-[390px]:mt-12 min-[390px]:gap-5 sm:grid-cols-2 lg:grid-cols-3">{teachers.data.items.map((teacher) => <article key={`${teacher.profile.display_name}-${teacher.milestone_days}`} className="min-w-0 overflow-hidden rounded-[22px] border border-white bg-white/90 p-4 shadow-[0_18px_50px_rgba(15,23,42,0.08)] backdrop-blur min-[390px]:rounded-3xl min-[390px]:p-6"><div className="flex items-start justify-between gap-3 min-[390px]:gap-4"><div className="h-16 w-16 shrink-0 overflow-hidden rounded-full bg-blue-50 ring-4 ring-white shadow-md min-[390px]:h-20 min-[390px]:w-20"><BoyAvatar avatarKey={teacher.profile.avatar_key} alt={`${teacher.profile.display_name}'s profile avatar`} /></div><TeachingBadge tier={teacher.badge_tier} label={teacher.badge_tier === "champion" ? "Champion" : "Gold Teacher"} compact /></div><h2 className="mt-4 break-words text-lg font-black text-slate-950 min-[390px]:mt-5 min-[390px]:text-xl">{teacher.profile.display_name}</h2><p className="mt-1 text-sm font-bold text-blue-600">{teacher.milestone_days}-day teaching streak</p><div className="mt-4 space-y-2 border-t border-slate-100 pt-4 text-xs font-semibold text-slate-600 min-[390px]:mt-5">{teacher.profile.school && <p className="flex min-w-0 items-start gap-2 break-words"><School className="h-4 w-4 shrink-0 text-slate-400" />{teacher.profile.school}</p>}{teacher.profile.district && <p className="flex min-w-0 items-start gap-2 break-words"><MapPin className="h-4 w-4 shrink-0 text-slate-400" />{teacher.profile.district}</p>}<p className="flex items-start gap-2"><Award className="h-4 w-4 shrink-0 text-amber-500" />Recognized {new Intl.DateTimeFormat("en-IN", { month: "long", year: "numeric" }).format(new Date(teacher.achievement_date))}</p></div></article>)}</section> : <div className="mx-auto mt-8 max-w-xl rounded-[22px] border border-blue-100 bg-white/90 p-5 text-center shadow-sm min-[390px]:mt-12 min-[390px]:rounded-3xl min-[390px]:p-8"><Award className="mx-auto h-8 w-8 text-blue-500 min-[390px]:h-9 min-[390px]:w-9" /><h2 className="mt-4 text-base font-black text-slate-900 min-[390px]:text-lg">The recognition wall is ready</h2><p className="mt-2 text-xs leading-5 text-slate-500 min-[390px]:text-sm min-[390px]:leading-6">Approved Gold and Champion Teacher profiles will appear here. No teacher information is ever published automatically.</p></div>}
      </div>
    </main>
  );
}
