"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, CalendarDays, Check, Copy, Plus, School, Trash2 } from "lucide-react";
import { backendApi, type PrimaryAcademicYear, type PrimaryCurriculumLesson } from "@/lib/api";
import { curriculumHref, levelLabel, SCHOOL_LEVELS } from "@/lib/school-admin-curriculum";
import { academicYearState, yearReadiness } from "@/lib/school-admin-support";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { useToast } from "@/components/ui/toast";
import { ActionDialog, ConfirmDialog } from "@/components/school-admin/shared/action-dialog";
import { PageError, PageHeading, SchoolAdminPage } from "@/components/school-admin/shared/page-primitives";
import { getErrorMessage } from "@/lib/errors";
import { cn } from "@/lib/utils";

type StartMode = "teachpad" | "copy" | "empty";

export function AcademicYearsWorkspace() {
  const queryClient = useQueryClient(); const { toast } = useToast(); const [createOpen, setCreateOpen] = useState(false); const [activate, setActivate] = useState<PrimaryAcademicYear | null>(null); const [remove, setRemove] = useState<PrimaryAcademicYear | null>(null); const [busy, setBusy] = useState(false);
  const years = useQuery<PrimaryAcademicYear[]>({ queryKey: ["school-admin", "academic-years"], queryFn: backendApi.schoolAdminAcademicYears });
  const lessonSets = useQuery<Record<string, PrimaryCurriculumLesson[]>>({ queryKey: ["school-admin", "academic-year-readiness", (years.data ?? []).map((year) => year.id).join(",")], queryFn: async () => Object.fromEntries(await Promise.all((years.data ?? []).map(async (year) => [year.id, await backendApi.schoolAdminCurriculum({ academic_year_id: year.id })]))), enabled: Boolean(years.data?.length) });
  const ordered = useMemo(() => (years.data ?? []).slice().sort((a, b) => {
    const rank = { current: 0, planning: 1, completed: 2 }; const byState = rank[academicYearState(a)] - rank[academicYearState(b)]; return byState || b.starts_on.localeCompare(a.starts_on);
  }), [years.data]);
  async function refresh() { await queryClient.invalidateQueries({ queryKey: ["school-admin", "academic-years"] }); await queryClient.invalidateQueries({ queryKey: ["school-admin", "academic-year-readiness"] }); }
  async function makeCurrent() { if (!activate) return; setBusy(true); try { await backendApi.schoolAdminUpdateAcademicYear(activate.id, { is_active: true }); await refresh(); toast({ title: `${activate.name} is now current`, description: "School admin and teacher curriculum now resolve against this academic year." }); setActivate(null); } catch (error: any) { toast({ title: "Could not switch academic year", description: error?.message, variant: "error" }); } finally { setBusy(false); } }
  // The service refuses a year that is current or still referenced, so the
  // error it returns is the explanation — surface it rather than a generic one.
  async function deleteYear() { if (!remove) return; setBusy(true); try { await backendApi.schoolAdminDeleteAcademicYear(remove.id); await refresh(); toast({ title: `${remove.name} deleted`, description: "The academic year had no curriculum, classes or assignments." }); setRemove(null); } catch (error: any) { toast({ title: "Could not delete academic year", description: getErrorMessage(error, "Move or remove its curriculum, classes and assignments first."), variant: "error" }); } finally { setBusy(false); } }
  return <SchoolAdminPage>
    <PageHeading eyebrow="School calendar" title="Academic Years" description="Keep planning, published curriculum, and teacher access in the right school-year context." actions={<Button onClick={() => setCreateOpen(true)}><Plus className="h-4 w-4" /> Create academic year</Button>} />
    {years.isError || lessonSets.isError ? <PageError description="Academic years and curriculum readiness could not be loaded." onRetry={() => { void years.refetch(); void lessonSets.refetch(); }} /> : years.isLoading ? <div className="grid gap-4 lg:grid-cols-2">{[0, 1].map((item) => <Skeleton key={item} className="h-80 rounded-3xl" />)}</div> : ordered.length ? <div className="grid gap-4 lg:grid-cols-2">{ordered.map((year) => <YearCard key={year.id} year={year} lessons={lessonSets.data?.[year.id] ?? []} onActivate={() => setActivate(year)} onDelete={() => setRemove(year)} />)}</div> : <div className="rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><CalendarDays className="mx-auto h-7 w-7 text-slate-400" /><h2 className="mt-3 text-lg font-semibold text-slate-950">Set up your first academic year</h2><p className="mt-2 text-sm text-slate-500">This gives drafts and published curriculum a clear school context.</p><Button className="mt-5" onClick={() => setCreateOpen(true)}>Create academic year</Button></div>}
    <CreateYearDialog open={createOpen} onOpenChange={setCreateOpen} currentYear={years.data?.find((year) => year.is_active)} onCreated={refresh} />
    <ConfirmDialog open={Boolean(activate)} onOpenChange={(open) => { if (!open) setActivate(null); }} busy={busy} onConfirm={makeCurrent} title={`Make ${activate?.name ?? "this year"} current?`} description="This changes the default curriculum context across school admin and teacher-facing primary workflows. Existing curriculum is not deleted." confirmLabel="Make current" />
    <ConfirmDialog open={Boolean(remove)} onOpenChange={(open) => { if (!open) setRemove(null); }} busy={busy} onConfirm={deleteYear} title={`Delete ${remove?.name ?? "this year"}?`} description="This permanently removes the academic year. It only succeeds while the year has no teaching days, classes or teacher assignments, and is not the current year." confirmLabel="Delete year" />
  </SchoolAdminPage>;
}

function YearCard({ year, lessons, onActivate, onDelete }: { year: PrimaryAcademicYear; lessons: PrimaryCurriculumLesson[]; onActivate: () => void; onDelete: () => void }) {
  const state = academicYearState(year); const displayLevels = SCHOOL_LEVELS.slice(0, 3);
  return <article className={cn("rounded-3xl border bg-white p-5 sm:p-6", state === "current" ? "border-blue-300 shadow-[0_12px_30px_rgba(37,99,235,0.08)]" : "border-slate-200")}><div className="flex items-start justify-between gap-4"><div><span className={cn("inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold uppercase tracking-wide", state === "current" ? "bg-blue-50 text-blue-700" : state === "planning" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-500")}>{state}</span><h2 className="mt-3 text-xl font-semibold tracking-tight text-slate-950">{year.name}</h2><p className="mt-1 text-sm text-slate-500">{formatDate(year.starts_on)} – {formatDate(year.ends_on)}</p></div><CalendarDays className={cn("h-6 w-6", state === "current" ? "text-blue-600" : "text-slate-300")} /></div><div className="mt-6 space-y-3"><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-400">Curriculum readiness</p>{displayLevels.map((level) => { const readiness = yearReadiness(lessons, level.value); return <div key={level.value}><div className="mb-1.5 flex items-center justify-between text-xs"><span className="font-semibold text-slate-700">{level.label}</span><span className="text-slate-500">{readiness.ready} days ready</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-500" style={{ width: `${Math.max(readiness.ready ? 2 : 0, readiness.percent)}%` }} /></div></div>; })}</div><div className="mt-6 flex flex-wrap gap-2 border-t border-slate-100 pt-4"><Link href={curriculumHref({ year: year.id, level: "nursery" })} className="inline-flex h-8 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold text-slate-800 hover:border-blue-200 hover:text-blue-700">Open curriculum <ArrowRight className="h-4 w-4" /></Link>{state !== "current" ? <><Button size="sm" onClick={onActivate}>Make current</Button><Button size="sm" variant="outline" className="text-rose-600 hover:bg-rose-50" onClick={onDelete}><Trash2 className="h-3.5 w-3.5" /> Delete</Button></> : <span className="inline-flex items-center gap-1.5 px-2 text-xs font-semibold text-emerald-700"><Check className="h-4 w-4" /> Default school year</span>}</div></article>;
}

function CreateYearDialog({ open, onOpenChange, currentYear, onCreated }: { open: boolean; onOpenChange: (open: boolean) => void; currentYear?: PrimaryAcademicYear; onCreated: () => Promise<void> }) {
  const { toast } = useToast(); const now = new Date(); const suggestedStart = `${now.getFullYear()}-06-01`; const suggestedEnd = `${now.getFullYear() + 1}-05-31`;
  const [name, setName] = useState(`${now.getFullYear()}–${String(now.getFullYear() + 1).slice(-2)}`); const [start, setStart] = useState(suggestedStart); const [end, setEnd] = useState(suggestedEnd); const [mode, setMode] = useState<StartMode>("teachpad"); const [busy, setBusy] = useState(false);
  async function create() { if (!name.trim() || !start || !end) return; setBusy(true); try { const year = await backendApi.schoolAdminCreateAcademicYear({ name: name.trim(), starts_on: start, ends_on: end, is_active: false }); let cloned = 0; /* Persist the choice. "teachpad" and "empty" used to differ only in the toast below — the mode never left the browser, so "Start empty" still inherited the master. "copy" duplicates this school's own work and leaves the master read-through as it is. */ if (mode !== "copy") { await backendApi.schoolAdminSetCurriculumStartingPoint(mode === "empty" ? "empty" : "teachpad"); } if (mode === "copy" && currentYear) { const result = await backendApi.schoolAdminCloneAcademicYear(currentYear.id, { destination_year_id: year.id, include_drafts: true, include_published: true, include_resources: true }); cloned = result.cloned_count; } await onCreated(); onOpenChange(false); toast({ title: `${year.name} created`, description: mode === "copy" ? `${cloned} school teaching days were copied as drafts.` : mode === "teachpad" ? "TeachPad's current master curriculum is available as the starting point." : "The year is empty and ready for school planning." }); } catch (error: any) { toast({ title: "Could not create academic year", description: error?.message, variant: "error" }); } finally { setBusy(false); } }
  return <ActionDialog open={open} onOpenChange={onOpenChange} title="Create academic year" description="Choose the dates and how curriculum planning should begin." size="lg" footer={<><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={busy || !name.trim() || !start || !end} onClick={() => void create()}>{busy ? "Creating…" : "Create year"}</Button></>}><div className="grid gap-4 sm:grid-cols-3"><label className="text-sm font-semibold sm:col-span-3">Year name<Input autoFocus className="mt-2" value={name} onChange={(event) => setName(event.target.value)} /></label><label className="text-sm font-semibold sm:col-span-1">Starts<Input type="date" className="mt-2" value={start} onChange={(event) => setStart(event.target.value)} /></label><label className="text-sm font-semibold sm:col-span-1">Ends<Input type="date" className="mt-2" value={end} onChange={(event) => setEnd(event.target.value)} /></label></div><fieldset className="mt-6"><legend className="text-sm font-semibold text-slate-900">Start curriculum with</legend><div className="mt-3 grid gap-3 sm:grid-cols-3"><ModeCard active={mode === "teachpad"} onClick={() => setMode("teachpad")} icon={School} title="TeachPad curriculum" description="Inherit the current master curriculum without copying it." /><ModeCard active={mode === "copy"} disabled={!currentYear} onClick={() => setMode("copy")} icon={Copy} title="Copy current year" description={currentYear ? `Copy ${currentYear.name} school work as editable drafts.` : "No current school year to copy."} /><ModeCard active={mode === "empty"} onClick={() => setMode("empty")} icon={Plus} title="Start empty" description="Build every school teaching day from scratch." /></div></fieldset></ActionDialog>;
}

function ModeCard({ active, disabled, onClick, icon: Icon, title, description }: { active: boolean; disabled?: boolean; onClick: () => void; icon: typeof School; title: string; description: string }) { return <button type="button" disabled={disabled} onClick={onClick} className={cn("rounded-2xl border p-4 text-left transition disabled:cursor-not-allowed disabled:opacity-50", active ? "border-blue-500 bg-blue-50" : "border-slate-200 hover:border-slate-300")}><Icon className={cn("h-5 w-5", active ? "text-blue-600" : "text-slate-400")} /><span className="mt-3 block text-sm font-semibold text-slate-900">{title}</span><span className="mt-1 block text-xs leading-5 text-slate-500">{description}</span></button>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-IN", { month: "short", year: "numeric" }).format(new Date(`${value}T00:00:00`)); }
